stages:
  - build

variables:
  TAGGER_IMAGE_TAG: $CI_REGISTRY_IMAGE/tagging:$CI_COMMIT_REF_SLUG

vgac_tagging:
  only:
    changes:
      - vgac_tagging/**/*
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - cd vgac_tagging
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat $CA_PUB_CERT_CHAIN >> /kaniko/ssl/certs/ca-certificates.crt
    - /kaniko/executor --context $CI_PROJECT_DIR/vgac_tagging --dockerfile $CI_PROJECT_DIR/vgac_tagging/Dockerfile --destination $TAGGER_IMAGE_TAG
  stage: build

# deploy-cs1:
#   stage: deploy
#   only:
#     refs: ["master"]
#     changes:
#       - vgac_tagging/**/*
#       - .gitlab-ci.yml
#   image: bash
#   environment:
#     name: cs1
#     url: https://pom-itb-cs1.campus.pomona.edu
#   script: |
#     apk update; apk add openssh-client
#     cd vgac_tagging
#     chmod 600 $PRIVATE_KEY
#     scp -i $PRIVATE_KEY \
#       -o UserKnownHostsFile=/dev/null \
#       -o StrictHostKeyChecking=no  \
#       docker-compose.deploy.yml \
#       faim@pom-itb-cs1.campus.pomona.edu:~/tagging/docker-compose.yml
#     ssh faim@pom-itb-cs1.campus.pomona.edu \
#       -o UserKnownHostsFile=/dev/null \
#       -o StrictHostKeyChecking=no \
#       -i $PRIVATE_KEY "
#      cd ~faim/tagging
#      echo 'Docker login'
#      docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY || exit 1
#      echo 'Pull images'
#      TAGGER_IMAGE=$TAGGER_IMAGE_TAG \
#        docker-compose pull
#      echo 'Using docker-compose up'
#      POSTGRES_USER=$POSTGRES_USER \
#        POSTGRES_DB=$POSTGRES_DB \
#        POSTGRES_URL=$POSTGRES_URL \
#        POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
#        POSTGRES_PORT=$POSTGRES_PORT \
#        TAGGER_IMAGE=$TAGGER_IMAGE_TAG \
#        docker-compose up -d"
