stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
    
vgac_tagging:
  image:
    name: ?
    entrypoint: ?
  script:?
   
  stage: build

deploy-grade01:
  stage: deploy
  only:
    refs: ["master"]
  image: bash
  environment:
    name: ?
    url: ?
  script: |
    apk update 
    ssh ?@pom-itb-grade01.campus.pomona.edu \
    -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no \
    -i $PRIVATE_KEY "
    cd ~?
    echo “Docker login”
    docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    echo “Pull”
    # TODO use docker-compose
    docker pull $IMAGE_TAG
    docker volume create ?
    docker volume create ?
    echo “Restart ?”
    docker stop -t 5 ?
    sleep 6
    docker container rm ?
    docker run -d --name ? \
      $IMAGE_TAG"
