version: "3.4"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["./scripts/wait-for-it.sh", "postgres:5432", "--", "./scripts/docker_script.sh"]
    environment:
      - FLASK_ENV=docker
    ports:
      - "5000:80"
    depends_on:
      - postgres

volumes:
  flask-app-db:
    name: flask-app-db
